# Generated by Django 3.2 on 2023-03-28 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230328_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
