# Generated by Django 3.2.4 on 2023-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_record_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
